CREATE TABLE product (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug             VARCHAR(100) NOT NULL UNIQUE,
    name             VARCHAR(200) NOT NULL,
    package_quantity INTEGER NOT NULL CHECK (package_quantity > 0),
    package_unit     VARCHAR(20) NOT NULL,
    price            DECIMAL(10, 2) NOT NULL CHECK (price >= 0),
    currency         CHAR(3) NOT NULL
);
