CREATE TABLE product (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug             VARCHAR(100) NOT NULL UNIQUE CHECK (slug REGEXP '^[a-z0-9]+(-[a-z0-9]+)*$'),
    name             VARCHAR(200) NOT NULL CHECK (name REGEXP '.*\S.*'),
    package_quantity INTEGER NOT NULL CHECK (package_quantity > 0),
    package_unit     ENUM('g', 'kg', 'ml') NOT NULL,
    price            DECIMAL(10, 2) NOT NULL CHECK (price > 0)
);
